services:

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: aisel-postgres

    environment:
      POSTGRES_USER: aisel
      POSTGRES_PASSWORD: Ibilola1976*
      POSTGRES_DB: observability

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  api:
    build:
      context: ./apps/api

    container_name: aisel-api

    ports:
      - "8000:8000"

    env_file:
      - ./apps/api/.env

    depends_on:
      - postgres

    restart: always

  web:
    build:
      context: ./apps/web

    container_name: aisel-web

    ports:
      - "3000:8000"

    env_file:
      - ./apps/web/.env

    depends_on:
      - api

    restart: always

volumes:
  postgres_data: